env:
  path: ${HOME}/d2k
log:
  level: ${D2K_CONFIG_LOG_LEVEL:-debug}
  verbose: ${D2K_CONFIG_LOG_VERBOSE:-true}
  trace: ${D2K_CONFIG_LOG_TRACE:-true}
network:
  external_ip: $(network_cli dns external_ip | tail -1) # "$(dig +short txt ch whoami.cloudflare @1.0.0.1)" # $(network_cli dns external_ip)
  dns:
    zone: ${D2K_CONFIG_NETWORK_DNS_ZONE:-raphaelcarlosr.com}
    provider: ${D2K_CONFIG_NETWORK_DNS_ZONE:-cloudflare}    # cloudflare, gcp, route53, selfsigned
cluster:
  name: ${D2K_CONFIG_CLUSTER_NAME:-d2k-default}
  ha: false
  servers:
    nodes: ${D2K_CONFIG_CLUSTER_SERVERS_NODES:-1}
    memory: ${D2K_CONFIG_CLUSTER_SERVERS_MEMORY:-2048MiB}
  agents:
    nodes: ${D2K_CONFIG_CLUSTER_AGENTS_NODES:-1}
    memory: ${D2K_CONFIG_CLUSTER_AGENTS_MEMORY:-2048MiB}
  network:
    name: ${D2K_CONFIG_CLUSTER_NAME}-net
    internal:
      host: ${D2K_CONFIG_CLUSTER_NAME}.${D2K_CONFIG_NETWORK_DNS_ZONE}.local
    external:
      host: ${D2K_CONFIG_CLUSTER_NAME}.${D2K_CONFIG_NETWORK_DNS_ZONE}      
  api:
    host: ${D2K_CONFIG_CLUSTER_NETWORK_INTERNAL_HOST:-localhost}
    ip: ${D2K_CONFIG_CLUSTER_API_IP:-127.0.0.1}
    port: ${D2K_CONFIG_CLUSTER_API_PORT:-5510}
  ports:
    http: ${D2K_CONFIG_CLUSTER_PORTS_HTTP:-$(network_cli ports available 80-80 | tail -1 )}
    https: ${D2K_CONFIG_CLUSTER_PORTS_HTTPS:-$(network_cli ports available 443-443 | tail -1 )}

  
  