---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: homelab-issuer
spec:
  acme:
    email: $LETSENCRYPT_EMAIL
    privateKeySecretRef:
      name: issuer-account-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          cloudflare:
            email: $HL_CF_EMAIL
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token
      selector:
        dnsNames:
        - '${HL_CLUSTER_DOMAIN}'
        - '*.${HL_CLUSTER_DOMAIN}'
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: homelab-issuer-staging
spec:
  acme:
    email: $LETSENCRYPT_EMAIL
    privateKeySecretRef:
      name: issuer-account-key
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          cloudflare:
            email: $HL_CF_EMAIL
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token
      selector:
        dnsNames:
        - '${HL_CLUSTER_DOMAIN}'
        - '*.${HL_CLUSTER_DOMAIN}'