---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: homelab-issuer
spec:
  acme:
    email: $LETSENCRYPT_EMAIL
    privateKeySecretRef:
      name: issuer-account-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          cloudDNS:
            project: $HL_GCP_PROJECT_ID
            serviceAccountSecretRef:
              name: clouddns-dns01-solver
              key: key.json